name: autofix.ci

on:
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  autofix:
    name: Lints, handles new assets, and commits changes
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Convert new assets to svg
        if: ${{ !cancelled() }}
        run: pnpm convert-new-assets-to-svg

      - name: Clean assets
        if: ${{ !cancelled() }}
        run: pnpm clean-assets

      - name: Sort
        if: ${{ !cancelled() }}
        run: pnpm sort

      - name: Prettier
        if: ${{ !cancelled() }}
        run: pnpm format

      - name: Type check
        if: ${{ !cancelled() }}
        run: pnpm type-check

      - name: Commit clean assets
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
